platform :ios, '12.0'

source 'git@github.com:Bose/BoseWearableSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'GestureExample' do
  use_frameworks!

  pod 'BoseGesture', :path => '../../'
  pod 'BoseWearable'
end

